version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      web-runtime:
        dependency-type: production
      web-development:
        dependency-type: development

  - package-ecosystem: nuget
    directory: /server
    schedule:
      interval: weekly
    open-pull-requests-limit: 5

  - package-ecosystem: gradle
    directory: /android-tv
    schedule:
      interval: weekly
    open-pull-requests-limit: 5

  - package-ecosystem: docker
    directory: /server/LessonCue.Server
    schedule:
      interval: weekly
    open-pull-requests-limit: 3

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
